# Site settings
title: Audio Kit
email: aure@hearforyourself.com
description: > # Test
  test
url: "http://audiokit.io" # the base hostname & protocol for your site
twitter_username: AudioKitMan
github_username:  AudioKit

# Build settings
markdown: kramdown
